# Generated by Django 2.1 on 2019-02-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateproject',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='uploaded_images/djangodbmodelsfieldscharfield/', verbose_name='Image'),
        ),
    ]
