# Generated by Django 2.1 on 2019-02-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_realestateproject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateproject',
            name='description',
            field=models.TextField(default='This is sample description'),
            preserve_default=False,
        ),
    ]
