# Generated by Django 2.1 on 2019-02-22 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_realestateproject_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='uploaded_images/%Y/%m/%d/', verbose_name='Image')),
                ('section_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.SectionProject')),
            ],
        ),
        migrations.AlterField(
            model_name='realestateproject',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='uploaded_images/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
